# Generated by Django 6.0.5 on 2026-05-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroObservatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('social', 'Social / Demográfico'), ('economico', 'Económico / Comercial'), ('ambiental', 'Ambiental / Agrícola'), ('seguridad', 'Seguridad / Infraestructura')], max_length=20)),
                ('valor', models.FloatField()),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
