# Generated by Django 6.0.5 on 2026-05-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTurista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_personas', models.IntegerField(default=1, verbose_name='Número de personas')),
                ('tipo_procedencia', models.CharField(choices=[('nacional', 'Nacional'), ('extranjero', 'Extranjero')], default='nacional', max_length=15, verbose_name='Tipo de Procedencia')),
                ('lugar_nacional', models.CharField(blank=True, choices=[('quito', 'Quito'), ('cuenca', 'Cuenca'), ('guayaquil', 'Guayaquil'), ('baleares', 'Baleares'), ('zona_sierra', 'Zona Sierra'), ('zona_costa', 'Zona Costa'), ('zona_oriente', 'Zona Oriente'), ('galapagos', 'Galápagos'), ('biblian', 'Biblián (Mancomunidad)'), ('canar', 'Cañar (Mancomunidad)'), ('el_tambo', 'El Tambo (Mancomunidad)'), ('suscal', 'Suscal (Mancomunidad)')], max_length=50, null=True, verbose_name='Lugar Nacional')),
                ('lugar_extranjero', models.CharField(blank=True, choices=[('estados_unidos', 'Estados Unidos'), ('america_n', 'América del Norte (Otros)'), ('america_s', 'América del Sur'), ('austria', 'Austria'), ('belgica', 'Bélgica'), ('escandinavia', 'Escandinavia'), ('francia', 'Francia'), ('holanda', 'Holanda'), ('italia', 'Italia'), ('paises_asiaticos', 'Países Asiáticos'), ('paises_este', 'Países del Este'), ('portugal', 'Portugal'), ('reino_unido', 'Reino Unido'), ('suiza', 'Suiza'), ('otros_ext', 'Otros Países')], max_length=50, null=True, verbose_name='País Extranjero')),
                ('motivo_visita', models.CharField(choices=[('hoteles', 'Hoteles / Alojamiento'), ('campings', 'Campings'), ('apart_bungal', 'Apartamentos / Bungalows'), ('balnearios', 'Balnearios'), ('turismo_rural', 'Turismo Rural'), ('rutas_senderos', 'Rutas / Senderismo'), ('parques_naturales', 'Parques Naturales / Monumentos'), ('gastronomia', 'Gastronomía'), ('act_culturales', 'Actividades Culturales'), ('fiestas', 'Fiestas / Eventos'), ('artesanian', 'Artesanía'), ('ocio', 'Ocio / Recreación'), ('act_deportivas', 'Actividades Deportivas'), ('info_local', 'Información Local'), ('otros', 'Otros Motivos')], max_length=50, verbose_name='¿Qué actividad o motivo realizan?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
        ),
    ]
