# Generated by Django 6.0.5 on 2026-05-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroturista',
            name='lugar_extranjero',
        ),
        migrations.RemoveField(
            model_name='registroturista',
            name='lugar_nacional',
        ),
        migrations.RemoveField(
            model_name='registroturista',
            name='motivo_visita',
        ),
        migrations.RemoveField(
            model_name='registroturista',
            name='numero_personas',
        ),
        migrations.RemoveField(
            model_name='registroturista',
            name='tipo_procedencia',
        ),
        migrations.AddField(
            model_name='registroturista',
            name='lugar_especifico',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroturista',
            name='motivo_viaje',
            field=models.CharField(choices=[('turismo_rural', 'Turismo Rural'), ('visita_familiar', 'Visita Familiar'), ('paso', 'Paso')], default='paso', max_length=50),
        ),
        migrations.AddField(
            model_name='registroturista',
            name='num_personas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='registroturista',
            name='procedencia',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('extranjero', 'Extranjero')], default='nacional', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroturista',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
