# Generated by Django 6.0.5 on 2026-06-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistas', '0002_remove_registroturista_lugar_extranjero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroturista',
            name='motivo_otro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registroturista',
            name='tipo_visita',
            field=models.CharField(choices=[('individual', 'Visitantes Individuales'), ('grupo', 'Grupo')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroturista',
            name='motivo_viaje',
            field=models.CharField(choices=[('hospedaje', 'Hospedaje'), ('gastronomia', 'Gastronomía'), ('compras', 'Compras'), ('negocios', 'Negocios'), ('turismo_rural', 'Turismo Rural'), ('rutas_senderos', 'Rutas/Senderos'), ('par_naturales', 'Par. Naturales'), ('religioso', 'Religioso/Peregrinación'), ('a_culturales', 'A. Culturales'), ('fiestas', 'Fiestas'), ('artesania', 'Artesanía'), ('ocio', 'Ocio'), ('a_deportivas', 'A. Deportivas'), ('transportes', 'Transportes'), ('biblian', 'Biblián'), ('canar', 'Cañar'), ('el_tambo', 'El Tambo'), ('suscal', 'Suscal'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
