# Generated by Django 6.0.5 on 2026-06-04 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turistas', '0003_registroturista_motivo_otro_and_more'),
    ]

    operations = [
    ]
