# Generated by Django 6.0.5 on 2026-06-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistas', '0004_agregar_tipo_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroturista',
            name='composicion_grupo',
            field=models.CharField(blank=True, choices=[('pareja', 'En Pareja'), ('familia', 'En Familia'), ('amigos', 'Con Amigos'), ('trabajo', 'Actividades de Trabajo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registroturista',
            name='estadia_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroturista',
            name='estadia_noches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroturista',
            name='medio_transporte',
            field=models.CharField(blank=True, choices=[('vehiculo_propio', 'Vehículo Propio'), ('bus_publico', 'Bus Público'), ('transporte_turistico', 'Transporte Turístico')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registroturista',
            name='rango_edad',
            field=models.CharField(blank=True, choices=[('jovenes', 'Jóvenes (16 a 25 años)'), ('adultos', 'Adultos (26 a 50 años)'), ('adultos_mayores', '51 años en adelante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registroturista',
            name='tipo_visita',
            field=models.CharField(choices=[('individual', 'Visitantes'), ('grupo', 'Grupo')], default='individual', max_length=20),
        ),
    ]
