# Generated by Django 6.0.5 on 2026-06-10 03:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistas', '0005_registroturista_composicion_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroturista',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registroturista',
            name='motivo_viaje',
            field=models.CharField(choices=[('hospedaje', 'Hospedaje'), ('gastronomia', 'Gastronomía'), ('compras', 'Compras'), ('negocios', 'Negocios'), ('turismo_rural', 'Turismo Rural'), ('rutas_senderos', 'Rutas/Senderos'), ('par_naturales', 'Par. Naturales'), ('religioso', 'Religioso/Peregrinación'), ('a_culturales', 'A. Culturales'), ('fiestas', 'Fiestas'), ('artesania', 'Artesanía'), ('ocio', 'Ocio'), ('a_deportivas', 'A. Deportivas'), ('transportes', 'Transportes'), ('biblian', 'Biblián'), ('canar', 'Cañar'), ('el_tambo', 'El Tambo'), ('suscal', 'Suscal'), ('ingapirca', 'Ingapirca'), ('banos_inca', 'Baños del Inca'), ('virgen_rocio', 'Virgen del Rocío'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
