# Generated by Django 6.0.5 on 2026-06-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistas', '0006_alter_registroturista_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroturista',
            name='lugar_detalle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
